---
- import_tasks: prerequisites/install-prerequisites.yml

- import_tasks: keys/apt-key.yml
  when: ansible_os_family == "Debian"

- import_tasks: keys/rpm-key.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"

- name: "(Install: Debian/Ubuntu/CentOS/RedHat/FreeBSD) Install NGINX"
  block:

    - import_tasks: opensource/install-oss.yml
      when: nginx_type == "opensource"

    - import_tasks: plus/install-plus.yml
      when: nginx_type == "plus"

    - import_tasks: modules/install-modules.yml
      when: true in modules.values()

    - import_tasks: conf/push-config.yml
      when: nginx_main_push_enable or nginx_http_push_enable or nginx_stream_push_enable

    - import_tasks: conf/template-config.yml
      when: nginx_main_template_enable or nginx_http_template_enable or nginx_stream_template_enable

    - import_tasks: conf/setup-status.yml
      when: nginx_status_enable

    - import_tasks: conf/setup-rest-api.yml
      when: nginx_rest_api_enable and nginx_type == "plus"

  when: nginx_enable

- import_tasks: amplify/install-amplify.yml
  when: nginx_amplify_enable and nginx_amplify_api_key is defined and nginx_amplify_api_key

- import_tasks: controller/install-controller.yml
  when: nginx_controller_enable and nginx_controller_api_key is defined and nginx_controller_api_key and nginx_controller_api_endpoint is defined and nginx_controller_api_endpoint

- import_tasks: unit/install-unit.yml
  when: nginx_unit_enable
