---
- import_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: "(Install: All OSs) Install NGINX Unit"
  package:
    name: unit
    state: present
  notify: "(Handler: All OSs) Start NGINX Unit"

- import_tasks: install-packages.yml
  when: unit_packages
