---
- name: "(CentOS/RedHat) Add Mainline NGINX Repository"
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/{{ item }}/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes
  with_items:
    - centos
    - rhel
  when: branch == "mainline"

- name: "(CentOS/RedHat) Add Stable NGINX Repository"
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/{{ item }}/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes
  with_items:
    - centos
    - rhel
  when: branch == "stable"
