---
- name: "(Install: CentOS/RedHat/Oracle Linux) Add NGINX Plus Repository"
  yum_repository:
    name: nginx-plus
    baseurl: https://plus-pkgs.nginx.com/centos/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Plus Repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: yes
    gpgcheck: yes
  when: ansible_distribution != "Amazon"

- name: "(Install: Amazon Linux) Add NGINX Plus Repository"
  yum_repository:
    name: nginx-plus
    baseurl: https://plus-pkgs.nginx.com/amzn/$releasever/$basearch
    description: NGINX Plus Repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: yes
    gpgcheck: yes
  when: ansible_distribution == "Amazon"
